CREATE DATABASE "Together.NET.v2";

CREATE USER admin WITH PASSWORD 'admin';

ALTER USER admin WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE "Together.NET.v2" TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO admin;