version: "3.8"
name: "together-env"

volumes:
  env-postgres-data: {}
  env-redis-data: {}

services:
  env-together-postgres:
    container_name: env-together-postgres
    image: postgres
    environment:
      - POSTGRES_DB=Together.NET.v2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - env-postgres-data:/var/lib/postgresql/data/
    
  env-together-redis:
    container_name: env-together-redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - env-redis-data:/data