version: "3.8"

volumes:
  prod-postgres-data: {}
  prod-redis-data: {}

services:
  prod-together-postgres:
    container_name: prod-together-postgres
    image: postgres
    environment:
      - POSTGRES_DB=Together.NET.v2
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=P@ssword
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - prod-postgres-data:/var/lib/postgresql/data/
  
  prod-together-redis:
    container_name: prod-together-redis
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf
      - prod-redis-data:/data
  
  prod-together-api:
    container_name: prod-together-api
    build:
      context: ..
      dockerfile: Together.Server/Together.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=ProductionDocker
    ports:
      - "5015:5000"
    restart: unless-stopped
    depends_on:
      - prod-together-postgres
      - prod-together-redis
  
  prod-together-nginx:
    container_name: prod-together-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ../Together.Proxy/nginx.production-docker.conf:/etc/nginx/conf.d/default.conf
      - ../Together.Client/dist/together.net:/usr/share/nginx/html
    links:
      - prod-together-api
    depends_on:
      - prod-together-api